spring:
  application:
    name: spirng-boot-mail

  mail:
    host: smtp.163.com #邮箱服务器地址
    username: shunyang1989@163.com
    password: csy19890727
    default-encoding: utf-8 #以谁来发送邮件

mail:
  fromMail:
   addr: shunyang1989@163.com

